[schema]
q1="""
select BA.bank_name, BA.alias, datetime, recipient, withdraw, saving, balance, user_note, bank_note, category from "Transaction"
inner join BankAccount BA on BA.id = "Transaction".bank_id
order by BA.bank_name, BA.alias
"""